# Generated by Django 2.2.5 on 2021-02-11 16:33

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('address', models.CharField(default='', max_length=200)),
                ('home_photo', models.ImageField(upload_to='')),
                ('instagram_id', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=20, null=True)),
                ('daily_available_hours', models.IntegerField(default=10, help_text='How much time per day can you spend with the cat?')),
                ('weekend_available_hours', models.IntegerField(default=10, help_text='How much time per weekend can you spend with the cat?')),
                ('married', models.BooleanField(default=True)),
                ('family_members', models.CharField(default='', help_text='Please describe the family members living with you. (Ex. Spouse, 2 teenagers)', max_length=100)),
                ('companion_aminals', models.CharField(default='', help_text='Please describe the companion animals living with you. (Ex. 1 Labrador Retriever, 2 Domestic Cats)', max_length=100)),
                ('family_agreement', models.BooleanField(default=False)),
                ('monthly_budget', models.IntegerField(default=500000)),
                ('urgent_budget', models.IntegerField(default=5000000)),
                ('budget_how', models.TextField(default='', help_text='Please tell us how you plan to finance your budget.')),
                ('protect_window', models.BooleanField(default=False)),
                ('protect_door', models.BooleanField(default=False)),
                ('first_ever_cat', models.BooleanField(default=False)),
                ('reason_adopt', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'House Types',
            },
        ),
    ]
