# Generated by Django 2.2.5 on 2021-02-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('is_neutered', models.BooleanField(default=False)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('estimated_age', models.CharField(default=0, max_length=10)),
                ('coat_length', models.CharField(choices=[('hairless', 'Hairless'), ('shor hair', 'Shorthair'), ('medium hair', 'Medium hair'), ('long hair', 'Longhair')], max_length=15)),
                ('rescue_story', models.TextField()),
                ('instagram_id', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tiktok_id', models.CharField(blank=True, max_length=20, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=300, null=True)),
                ('bro_sis', models.ManyToManyField(blank=True, related_name='_cat_bro_sis_+', to='cats.Cat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Characteristics',
            },
        ),
        migrations.CreateModel(
            name='CoatColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Coat Colors',
            },
        ),
        migrations.CreateModel(
            name='CoatPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Coat Patterns',
            },
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Markings',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='cat_photos')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cats.Cat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
