# Generated by Django 2.2.5 on 2021-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20210212_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='estimated_age',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
